# Generated by Django 4.0.2 on 2022-02-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vies_count',
            new_name='view_count',
        ),
    ]
